### ISSUE TITLE
Question RE: testing protocol

### ISSUE THREAD

**Issue by samehkamaleldin** [ttrouill/complex#3]
Hello Théo,

Thanks a lot for this piece of code, I've trying to understand the testing protocol from the code but unfortunately I couldn't.

I wonder what is the `positive to negative ratio` used in testing, and where to find that in the code. 

Thanks a lot

**Comment by samehkamaleldin** [comment]
I've found out that it compare to all possible entities, It's not straight forward in the code. But, from [this line](https://github.com/ttrouill/complex/blob/master/efe/evaluation.py#L226) we can see that it use the full entity embedding in the computation of scores that the score list corresponds to all possible entities.

**Comment by ttrouill** [comment]
Hi Mohamed,

Sorry for the latency, I'm currently in low-internet areas :)

So indeed, when there are only positive triples (as in WN18 and FB15K), the rankings are computed among all entities (as subject and as object) for the test triples. And yes, that's the ugly part of the code I'm not proud of, though for efficency purposes, I had to rewrite the scoring functions of the models. The reason is quite simple, the 'predict" function of the model objects (as used at [this line](https://github.com/ttrouill/complex/blob/master/efe/evaluation.py#L272) for genericity if you want to implement your own model for example) takes arrays of indexes in argument, and hence use [advanced indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html) that will make copies of the embeddings, even if the indexes are actually contiguous (it doesn't check). For the implemented models, that's why I reimplemented those specific scoring function that compute scores for all entities and that use the full entity embedding matrix as you pointed out, so that it is not copied at every score computation, and allows for computing validation scores quite often (every 50 iterations by default in the code), and thus allows for early stopping. That's the whole story :) However I could have done that in Theano too, but time urged as always, so this part is in numpy.
