### ISSUE TITLE
Print scores at index

### ISSUE THREAD

**Issue by Lirry** [ttrouill/complex#7]
Hello,
First off: great module! I just implemented it and it works like a charm with my own data. 
Now I want to do some error analysis by printing out the top 100 scores of certain relationship types.
Is there any build-in way to do that? 

Thanks,

**Comment by Lirry** [comment]
EDIT: What I want specifically, for a certain query in the testset: get all the scores (which has the length of n_entities)  Is this possible?

**Comment by ttrouill** [comment]
Hi Lirry,

Thanks! :)

So this touches to the ugly part of the code, have a look at the `compute_scores` function in `evaluation.py`, the functions you are looking for are defined inside: `generic_eval_s` and `generic_eval_o` to respectively compute the scores of all subject and all object entities.

Now these functions are quite slow as it uses indexes of all the entities instead of slicing in the
embedding matrices (see: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html),
but can be used for any model.
To avoid this problem I had to recode these functions for the models I wanted to be evaluated quickly,
by using slicing in the embedding matrices, see for example `rescal_eval_s` and `rescak_eval_o`. 
If you have your own model you can do the same, or maybe think of a more elegant solution ;)

**Comment by Lirry** [comment]
Hi Theo,

Thanks for your response! What I did is  I got in the for-loop containing 
`
				#Computing objects ranks
				res_obj = eval_o(i,j)`
And printed out the scores when my index (targeted result) was found. Is this still a correct method or are these no scores? Because when I printed these, the correct entity indeed was at the top.

Thanks

**Comment by ttrouill** [comment]
This is indeed a correct method :) , if you want only the scores for the object entity substitutions. If you want also all the subject entity substitution you need to printthe result of `eval_s` too!

Also this is the real valued score, if you are using a logistic model, you might want to print the logistic of this to get scores between 0 and 1.
